# Generated by Django 4.1 on 2022-09-02 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregated', '0002_alter_participants_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 13, 11, 27, 441384), verbose_name='date published'),
        ),
    ]
