# Generated by Django 4.1 on 2022-09-02 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregated', '0003_alter_participants_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 16, 16, 58, 823800), verbose_name='date published'),
        ),
    ]
