# Generated by Django 4.1 on 2022-09-02 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregated', '0004_alter_participants_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 2, 16, 20, 19, 861498), verbose_name='date published'),
        ),
    ]
