version: '3.9'

services:
  db:
    image: postgres:14-alpine
    networks:
      sonar-network:
        aliases:
          - db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql-data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    networks:
      sonar-network:
        aliases:
          - sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube-config:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - 9000:9000
    restart: always

networks:
  sonar-network:

volumes:
  postgresql:
  postgresql-data:
  sonarqube-config:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-bundled-plugins:
  