apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: bynet
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: bynet
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31001
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: bynet
spec:
  selector:
    app: database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---

