version: '3.9'

services:
    db:
        image: postgres:14-alpine
#        command: postgres -c listen_addresses='*'
        restart: always
        # volumes:
        #     - ./data/db:/var/lib/postgresql/data
        ports: 
            - 5432:5432
        environment: 
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_DB=${POSTGRES_DB}
    backend:
        image: moonlight234/bynet_attendance_back:dev-latest
        build:
            context: ./djangoProject
            dockerfile: Dockerfile
        restart: always
        ports: 
            - 8000:8000
        environment:
            - POSTGRES_NAME=${POSTGRES_NAME}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_PORT=${DATABASE_PORT}
            - BACKEND_PORT=${BACKEND_PORT}
            - REMOTE_HOST=${REMOTE_HOST}
            - REMOTE_PORT=${REMOTE_PORT}
            - REMOTE_USER=${REMOTE_USER}
            - REMOTE_PASSWORD=${REMOTE_PASSWORD}
            - REMOTE_FOLDER=${REMOTE_FOLDER}
            - ALLOW_HOSTS=web
        depends_on:
            - db
    web:
        image: moonlight234/bynet_attendance_front:dev-latest
        build:
            context: ./front_aggregate
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8080:80
        environment:
            - BACKEND_PORT=${BACKEND_PORT}
            - BACKEND_URL=${BACKEND_URL}
            - VUE_APP_TYPE=PROD
            # - VUE_APP_API_URL=backend
            # - VUE_APP_API_PORT=${VUE_APP_API_PORT}
        depends_on:
            - backend
