apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: {{ .Values.deployment.namespace }}-bynet-app
  labels:
    destiny: {{ .Values.deployment.namespace }}-bynet-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 70
status:
  currentReplicas: 1
  desiredReplicas: 1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: {{ .Values.deployment.namespace }}-bynet-app
  labels:
    destiny: {{ .Values.deployment.namespace }}-bynet-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
status:
  currentReplicas: 1
  desiredReplicas: 1
