apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.deployment.namespace }}-bynet-app
type: Opaque
data:
  postgres-user:        {{ .Values.deployment.postgresUser }}
  postgres-password:    {{ .Values.deployment.postgresPassword }}
  remote-user:          {{ .Values.deployment.remoteUser }}
  remote-password:      {{ .Values.deployment.remotePassword }}

